In [3]:
from pathlib import Path
import pandas as pd
import numpy as np

ROOT = Path.home() / "Desktop" / "FinCascade"
DATA_DIR = ROOT / "data"

print("Project root:", ROOT)
print("Data folder :", DATA_DIR)
print("Data folder exists:", DATA_DIR.exists())

Project root: C:\Users\Lenovo\Desktop\FinCascade
Data folder : C:\Users\Lenovo\Desktop\FinCascade\data
Data folder exists: True

In [4]:
prices = pd.read_csv(
    DATA_DIR / "market_prices_raw.csv",
    index_col=0,
    parse_dates=True
)

metadata = pd.read_csv(
    DATA_DIR / "entities.csv"
)

prices = prices.sort_index()

print("Prices shape:", prices.shape)
print("Entities:", len(metadata))
print("Date range:", prices.index.min(), "to", prices.index.max())

prices.head()

Prices shape: (1477, 26)
Entities: 26
Date range: 2021-01-01 00:00:00 to 2026-09-01 00:00:00

,AXISBANK.NS,BAJAJFINSV.NS,BAJFINANCE.NS,CL=F,DLF.NS,DRREDDY.NS,GC=F,GODREJPROP.NS,HCLTECH.NS,HDFCBANK.NS,...,MARUTI.NS,ONGC.NS,RELIANCE.NS,SBIN.NS,SUNPHARMA.NS,TCS.NS,TMPV.NS,WIPRO.NS,^NSEBANK,^NSEI
Date,,,,,,,,,,,,,,,,,,,,,
2021-01-01,620.727478,884.299316,514.064087,NaN,227.257492,1009.432129,NaN,1420.384277,751.725830,663.905701,...,7298.334473,67.063965,897.047119,253.242310,561.122314,2521.074463,181.694244,176.860580,31225.486328,14018.500000
2021-01-04,621.623108,887.120544,507.838013,47.619999,232.930588,1015.383057,1944.699951,1400.430664,775.373230,659.689514,...,7308.772461,69.762375,898.559143,254.737839,568.792114,2616.812012,186.370560,180.642960,31212.085938,14132.900391
2021-01-05,661.177307,879.354675,498.374847,49.930000,230.499252,1018.204407,1952.699951,1399.833618,784.033325,664.674316,...,7264.315918,68.323227,887.388306,255.372284,567.898132,2662.915283,188.221603,185.154510,31721.880859,14199.500000
2021-01-06,651.027527,875.915283,489.739227,50.630001,229.831848,1018.474304,1906.900024,1453.573853,773.633240,661.809143,...,7238.837402,69.762375,863.986084,258.363373,569.639160,2627.186279,190.364899,185.200073,31797.531250,14146.250000
2021-01-07,667.794495,896.017761,494.675323,50.830002,233.979385,1015.123108,1912.300049,1445.811401,761.255981,659.805847,...,7179.482910,70.445953,862.586975,260.765289,566.439392,2611.086182,191.680130,185.359558,31955.628906,14137.349609

In [5]:
prices = pd.read_csv(
    DATA_DIR / "market_prices_raw.csv",
    index_col=0,
    parse_dates=True
)

metadata = pd.read_csv(
    DATA_DIR / "entities.csv"
)

prices = prices.sort_index()

print("Prices shape:", prices.shape)
print("Entities:", len(metadata))
print("Date range:", prices.index.min(), "to", prices.index.max())

prices.head()

Prices shape: (1477, 26)
Entities: 26
Date range: 2021-01-01 00:00:00 to 2026-09-01 00:00:00

,AXISBANK.NS,BAJAJFINSV.NS,BAJFINANCE.NS,CL=F,DLF.NS,DRREDDY.NS,GC=F,GODREJPROP.NS,HCLTECH.NS,HDFCBANK.NS,...,MARUTI.NS,ONGC.NS,RELIANCE.NS,SBIN.NS,SUNPHARMA.NS,TCS.NS,TMPV.NS,WIPRO.NS,^NSEBANK,^NSEI
Date,,,,,,,,,,,,,,,,,,,,,
2021-01-01,620.727478,884.299316,514.064087,NaN,227.257492,1009.432129,NaN,1420.384277,751.725830,663.905701,...,7298.334473,67.063965,897.047119,253.242310,561.122314,2521.074463,181.694244,176.860580,31225.486328,14018.500000
2021-01-04,621.623108,887.120544,507.838013,47.619999,232.930588,1015.383057,1944.699951,1400.430664,775.373230,659.689514,...,7308.772461,69.762375,898.559143,254.737839,568.792114,2616.812012,186.370560,180.642960,31212.085938,14132.900391
2021-01-05,661.177307,879.354675,498.374847,49.930000,230.499252,1018.204407,1952.699951,1399.833618,784.033325,664.674316,...,7264.315918,68.323227,887.388306,255.372284,567.898132,2662.915283,188.221603,185.154510,31721.880859,14199.500000
2021-01-06,651.027527,875.915283,489.739227,50.630001,229.831848,1018.474304,1906.900024,1453.573853,773.633240,661.809143,...,7238.837402,69.762375,863.986084,258.363373,569.639160,2627.186279,190.364899,185.200073,31797.531250,14146.250000
2021-01-07,667.794495,896.017761,494.675323,50.830002,233.979385,1015.123108,1912.300049,1445.811401,761.255981,659.805847,...,7179.482910,70.445953,862.586975,260.765289,566.439392,2611.086182,191.680130,185.359558,31955.628906,14137.349609

In [6]:
# Use valid NIFTY 50 trading dates as the master calendar
nifty_dates = prices["^NSEI"].dropna().index

aligned_prices = prices.reindex(nifty_dates)

print("Original shape:", prices.shape)
print("Aligned shape :", aligned_prices.shape)

print("\nTop missing-value counts after alignment:")
print(
    aligned_prices.isna()
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

Original shape: (1477, 26)
Aligned shape : (1399, 26)

Top missing-value counts after alignment:
GC=F             46
CL=F             46
INR=X             4
^NSEBANK          1
BAJAJFINSV.NS     0
AXISBANK.NS       0
DRREDDY.NS        0
GODREJPROP.NS     0
DLF.NS            0
BAJFINANCE.NS     0
dtype: int64

In [7]:
# Forward-fill only short gaps caused by different market holidays
clean_prices = aligned_prices.ffill(limit=2)

# Drop any rows that still contain missing values
clean_prices = clean_prices.dropna().copy()

print("Aligned shape :", aligned_prices.shape)
print("Clean shape   :", clean_prices.shape)

print("\nRemaining missing values:")
print(clean_prices.isna().sum().sum())

clean_prices.to_csv(
    DATA_DIR / "market_prices_clean.csv"
)

print("\nSaved: market_prices_clean.csv")

Aligned shape : (1399, 26)
Clean shape   : (1398, 26)

Remaining missing values:
0

Saved: market_prices_clean.csv

In [8]:
returns = clean_prices.pct_change().dropna()

# Known Tata Motors demerger adjustment date
demerger_date = pd.Timestamp("2025-10-14")

if demerger_date in returns.index:
    returns.loc[demerger_date, "TMPV.NS"] = np.nan

# Model-ready dataset: remove rows containing any NaN
returns_model = returns.dropna().copy()

print("Returns shape       :", returns.shape)
print("Model-ready shape   :", returns_model.shape)

print("\nMissing values:")
print(returns_model.isna().sum().sum())

print("\nInfinite values:")
print(np.isinf(returns_model).sum().sum())

print("\nReturn range:")
print("Minimum:", returns_model.min().min())
print("Maximum:", returns_model.max().max())

Returns shape       : (1397, 26)
Model-ready shape   : (1396, 26)

Missing values:
0

Infinite values:
0

Return range:
Minimum: -0.1682506545721142
Maximum: 0.20446702847125153

In [9]:
returns.to_csv(
    DATA_DIR / "market_returns_clean.csv"
)

returns_model.to_csv(
    DATA_DIR / "market_returns_model.csv"
)

print("Saved:")
print("- market_returns_clean.csv")
print("- market_returns_model.csv")

print("\nModel dataset shape:", returns_model.shape)

Saved:
- market_returns_clean.csv
- market_returns_model.csv

Model dataset shape: (1396, 26)

In [10]:
asset_stats = pd.DataFrame({
    "mean_daily_return": returns_model.mean(),
    "daily_volatility": returns_model.std(),
    "annualized_return": returns_model.mean() * 252,
    "annualized_volatility": returns_model.std() * np.sqrt(252),
    "min_return": returns_model.min(),
    "max_return": returns_model.max()
})

print("Asset statistics created.")
print("Shape:", asset_stats.shape)

asset_stats.head()

Asset statistics created.
Shape: (26, 6)

,mean_daily_return,daily_volatility,annualized_return,annualized_volatility,min_return,max_return
AXISBANK.NS,0.000641,0.015998,0.161436,0.253960,-0.075701,0.090271
BAJAJFINSV.NS,0.000725,0.017520,0.182742,0.278124,-0.070792,0.114534
BAJFINANCE.NS,0.000704,0.018408,0.177477,0.292217,-0.077273,0.106350
CL=F,0.000801,0.025937,0.201973,0.411733,-0.164143,0.155453
DLF.NS,0.001001,0.021823,0.252200,0.346431,-0.122131,0.115966

In [11]:
meta_lookup = metadata.set_index("ticker")

asset_stats["name"] = asset_stats.index.map(
    meta_lookup["name"]
)

asset_stats["type"] = asset_stats.index.map(
    meta_lookup["type"]
)

asset_stats["sector"] = asset_stats.index.map(
    meta_lookup["sector"]
)

asset_stats = asset_stats[
    [
        "name",
        "type",
        "sector",
        "mean_daily_return",
        "annualized_return",
        "daily_volatility",
        "annualized_volatility",
        "min_return",
        "max_return"
    ]
]

asset_stats.head()

,name,type,sector,mean_daily_return,annualized_return,daily_volatility,annualized_volatility,min_return,max_return
AXISBANK.NS,Axis Bank,Company,Banking,0.000641,0.161436,0.015998,0.253960,-0.075701,0.090271
BAJAJFINSV.NS,Bajaj Finserv,Company,NBFC,0.000725,0.182742,0.017520,0.278124,-0.070792,0.114534
BAJFINANCE.NS,Bajaj Finance,Company,NBFC,0.000704,0.177477,0.018408,0.292217,-0.077273,0.106350
CL=F,Crude Oil,Commodity,Energy,0.000801,0.201973,0.025937,0.411733,-0.164143,0.155453
DLF.NS,DLF,Company,Realty,0.001001,0.252200,0.021823,0.346431,-0.122131,0.115966

In [12]:
volatility_table = asset_stats.sort_values(
    "annualized_volatility",
    ascending=False
)[
    [
        "name",
        "sector",
        "annualized_volatility"
    ]
].head(10).copy()

# Convert to percentage
volatility_table["annualized_volatility"] *= 100

volatility_table

                                         name   sector  annualized_volatility
CL=F                                Crude Oil   Energy              41.173262
GODREJPROP.NS               Godrej Properties   Realty              37.931611
TMPV.NS        Tata Motors Passenger Vehicles     Auto              35.052722
DLF.NS                                    DLF   Realty              34.643098
ONGC.NS                                  ONGC   Energy              31.273391
BAJFINANCE.NS                   Bajaj Finance     NBFC              29.221661
M&M.NS                    Mahindra & Mahindra     Auto              28.687879
BAJAJFINSV.NS                   Bajaj Finserv     NBFC              27.812413
SBIN.NS                                   SBI  Banking              26.341769
WIPRO.NS                                Wipro       IT              26.155334

In [13]:
asset_stats.to_csv(
    DATA_DIR / "asset_statistics.csv"
)

print("Saved: asset_statistics.csv")
print("Assets:", len(asset_stats))

Saved: asset_statistics.csv
Assets: 26

In [14]:
print("===== NOTEBOOK 02 SUMMARY =====")

print("\nEntities:")
print(len(metadata))

print("\nClean prices:")
print(clean_prices.shape)

print("\nClean returns:")
print(returns.shape)

print("\nModel-ready returns:")
print(returns_model.shape)

print("\nMissing values in model dataset:")
print(returns_model.isna().sum().sum())

print("\nInfinite values:")
print(np.isinf(returns_model).sum().sum())

print("\nFiles created:")

files = [
    "market_prices_clean.csv",
    "market_returns_clean.csv",
    "market_returns_model.csv",
    "asset_statistics.csv"
]

for file in files:
    path = DATA_DIR / file
    print(f"{file}: {path.exists()}")

===== NOTEBOOK 02 SUMMARY =====

Entities:
26

Clean prices:
(1398, 26)

Clean returns:
(1397, 26)

Model-ready returns:
(1396, 26)

Missing values in model dataset:
0

Infinite values:
0

Files created:
market_prices_clean.csv: True
market_returns_clean.csv: True
market_returns_model.csv: True
asset_statistics.csv: True